#!/usr/bin/env ruby
#
# rbc - Ruby Command Line Filter
#
# Inspired by https://github.com/thisredone/rb
#

def load_global_config_if_exists
  filespec = File.join(Dir.home, '.rbcrc')
  load(filespec) if File.exists?(filespec)
end


def execute(_, code)
  puts _.instance_eval(&code)
rescue Errno::EPIPE
  exit
end


load_global_config_if_exists
single_line = ARGV.delete('-l')
code = eval("Proc.new { #{ARGV.join(' ')} }")
single_line ? STDIN.each { |l| execute(l.chomp, code) } : execute(STDIN.each_line, code)

