#!/usr/bin/env ruby
#
# rexe - Ruby Command Line Executor Filter
#
# Inspired by https://github.com/thisredone/rb

require 'bundler'
require 'optparse'
require 'shellwords'

class Rexe < Struct.new(:input_mode, :loads, :output_mode, :requires, :verbose, :noop)

  VERSION = '0.10.0'

  def initialize
    clear_options
  end


  # Used as an initializer and also when `-!` is specified on the command line.
  def clear_options
    self.input_mode = :no_input
    self.output_mode = :puts
    self.loads = []
    self.requires = []
    self.verbose = false
    self.noop = false
    @output_formatter = nil
  end


  def help_text
    <<~HEREDOC

    rexe -- Ruby Command Line Executor/Filter -- v#{VERSION} -- https://github.com/keithrbennett/rexe

    Executes Ruby code on the command line, optionally taking standard input and writing to standard output.

    Options:

    -c  --clear_options        Clear all previous command line options specified up to now
    -h, --help                 Print help and exit
    -i, --input_mode MODE      Mode with which to handle input (i.e. what `self` will be in your code):
                                 -il line mode; each line is ingested as a separate string
                                 -ie enumerator mode
                                 -ib big string mode; all lines combined into single multiline string
                                 -in (default) no input mode; no special handling of input; self is not input 
    -l, --load RUBY_FILE(S)    Ruby file(s) to load, comma separated, or ! to clear
    -n, --[no-]noop            Do not execute the code (useful with -v); see note (1) below
    -o, --output_mode MODE     Output formatting mode (puts is default):
                                 'a' => awesome_print
                                 'i' => inspect
                                 'j' => json
                                 'J' => pretty_json
                                 'n' => no_output
                                 'p' => puts (default)
                                 's' => to_string
                                 'y' => yaml
    -r, --require REQUIRES     Gems and built-in libraries to require, comma separated, or ! to clear
    -v, --[no-]verbose         verbose mode (logs to stderr); see note (1) below

    If there is an .rexerc file in your home directory, it will be run as Ruby code 
    before processing the input.

    If there is a REXE_OPTIONS environment variable, its content will be prepended to the command line
    so that you can specify options implicitly (e.g. `export REXE_OPTIONS="-r awesome_print,yaml"`)

    (1) For boolean 'verbose' and 'noop' options, the following are valid:
    -v no, -v yes, -v false, -v true, -v n, -v y, -v +, but not -v -

    HEREDOC
  end


  def prepend_environment_options
    env_opt_string = ENV['REXE_OPTIONS']
    if env_opt_string
      args_to_prepend = Shellwords.shellsplit(env_opt_string)
      ARGV.unshift(args_to_prepend).flatten!
    end
  end


  def parse_command_line

    prepend_environment_options

    OptionParser.new do |parser|

      parser.on("-h", "--help", "Show help") do |_help_requested|
        puts help_text
        exit
      end

      parser.on('-l', '--load RUBY_FILE(S)', 'Ruby file(s) to load, comma separated, or ! to clear') do |v|
        if v == '!'
          self.loads.clear
        else
          loadfiles = v.split(',').map(&:strip)
          existent, nonexistent = loadfiles.partition { |filespec| File.exists?(filespec) }
          if nonexistent.any?
            log_if_verbose("\nDid not find the following files to load: #{nonexistent.to_s}\n\n")
          end
          existent.each { |filespec| self.loads << filespec }
        end
      end

      parser.on('-i', '--input_mode MODE',
                'Mode with which to handle input (-il, -ie, -ib, -in (default)') do |v|

        modes = {
            'l' => :line,
            'e' => :enumerator,
            'b' => :one_big_string,
            'n' => :no_input
        }

        self.input_mode = modes[v]
        if self.input_mode.nil?
          puts help_text
          raise "Input mode must be one of #{modes.keys}."
        end
      end

      parser.on('-o', '--output_mode MODE',
                'Mode with which to format values for output (-il, -ie, -ib, -in (default)') do |v|

        modes = {
            'a' => :awesome_print,
            'i' => :inspect,
            'j' => :json,
            'J' => :pretty_json,
            'n' => :no_output,
            'p' => :puts,         # default
            's' => :to_string,
            'y' => :yaml,
        }

        self.output_mode = modes[v]
        if self.output_mode.nil?
          puts help_text
          raise "Output mode must be one of #{modes.keys}."
        end
      end

      parser.on('-r', '--require REQUIRE(S)',
                'Gems and built-in libraries (e.g. shellwords, yaml) to require, comma separated, or ! to clear') do |v|
        if v == '!'
          self.requires.clear
        else
          v.split(',').map(&:strip).each { |r| self.requires << r }
        end
      end

      # See https://stackoverflow.com/questions/54576873/ruby-optionparser-short-code-for-boolean-option
      # for an excellent explanation of this optparse incantation.
      # According to the answer, valid options are:
      # -v no, -v yes, -v false, -v true, -v n, -v y, -v +, but not -v -.
      parser.on('-v', '--[no-]verbose [FLAG]', TrueClass, 'Verbose mode (logs to stderr)') do |v|
        self.verbose = (v.nil? ? true : v)
      end

      parser.on('-c', '--clear_options', "Clear all previous command line options") do |v|
        clear_options
      end

      parser.on('-n', '--[no-]noop [FLAG]', TrueClass, "Do not execute the code (useful with -v)") do |v|
        self.noop = (v.nil? ? true : v)
      end

      parser.on('', '--version', 'Print version') do
        puts VERSION
        exit
      end
    end.parse!

    requires.uniq!
    loads.uniq!

  end


  def load_global_config_if_exists
    filespec = File.join(Dir.home, '.rexerc')
    exists = File.exists?(filespec)
    if exists
      log_if_verbose("Loading global config file #{filespec}")
      load(filespec)
    end
    exists ? filespec : nil
  end


  def execute(eval_context_object, code)
    value = eval_context_object.instance_eval(&code)
    unless output_mode == :no_output
      print output_formatter.(value)
    end
  rescue Errno::EPIPE
    exit(-13)
  end


  def log_if_verbose(string)
    STDERR.puts(string) if verbose
  end


  def call
    start_time = Time.now

    parse_command_line

    log_if_verbose("rexe version #{VERSION} -- #{Time.now}")
    log_if_verbose('Source Code: ' + ARGV.join(' '))
    log_if_verbose('Options: ' + self.to_h.to_s)

    requires.each { |r| require(r) }

    load_global_config_if_exists

    loads.each { |file| load(file) }

    source_code = "Proc.new { #{ARGV.join(' ')} }"
    code = eval(source_code)

    actions = {
        line:           -> { STDIN.each { |l| execute(l.chomp, code) } },
        enumerator:     -> { execute(STDIN.each_line, code) },
        one_big_string: -> { big_string = STDIN.read; execute(big_string, code) },
        no_input:       -> { execute(Object.new, code) }
    }

    if self.noop
      log_if_verbose("No-op mode requested; not executing code.")
    else
      actions[input_mode].()
    end

    duration = Time.now - start_time
    log_if_verbose("rexe time elapsed: #{duration} seconds.")
  end
end


def output_formatter
  if @output_formatter.nil?

    if %i(json  pretty_json).include?(output_mode)
      require 'json'
    elsif output_mode == :yaml
      require 'yaml'
    elsif output_mode == :awesome_print
      require 'awesome_print'
    end

    formatters = {
        awesome_print: ->(obj)  { obj.ai },
        inspect:       ->(obj)  { obj.inspect + "\n" },
        json:          ->(obj)  { obj.to_json },
        no_output:     ->(_obj) { nil },
        pretty_json:   ->(obj)  { JSON.pretty_generate(obj) },
        puts:          ->(obj)  { sio = StringIO.new; sio.puts(obj); sio.string },   # default
        to_string:     ->(obj)  { obj.to_s + "\n" },
        yaml:          ->(obj)  { obj.to_yaml },
    }

    @output_formatter = formatters[output_mode]
  end
  @output_formatter
end


# This is needed because the gemspec file loads this file to access Rexe::VERSION
# and must not have it run at that time:
called_as_script = (File.basename($0) == File.basename(__FILE__))
if called_as_script
  Bundler.with_clean_env { Rexe.new.call }
end
